/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
"use client";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

const HatModel = React.memo(function HatModel(props) {
  // Use React.memo for performance optimization
  const { nodes, materials } = useGLTF("/models/hat-transformed.glb");

  const modelRef = useRef();

  useFrame(() => {
    modelRef.current.rotation.y += 0.007;
  });
  // return (
  //   <group
  //     {...props}
  //     dispose={null}
  //     ref={modelRef}
  //     scale={[1.8, 1.8, 1.8]}
  //     rotation={[0.4, -1, 0]}
  //     position={[0, 0, 0]}
  //   >
  //     <mesh
  //       castShadow
  //       receiveShadow
  //       geometry={nodes.Object_2.geometry}
  //       material={materials.initialShadingGroup}
  //       position={[0, -3.867, 0]}
  //       rotation={[-Math.PI / 2, 0, 0]}
  //     />
  //   </group>
  // );
  return (
    <group
      {...props}
      dispose={null}
      ref={modelRef}
      scale={[0.8, 0.8, 0.8]}
      rotation={[0.4, -1, 0]}
      position={[0, 0, 0]}
    >
      <mesh
        name="Group51664_0"
        castShadow
        receiveShadow
        geometry={nodes.Group51664_0.geometry}
        material={materials['Material.011']}
        position={[0.687, -0.348, 0.01]}
        rotation={[1.068, 0, -0.362]}
      />
      <mesh
        name="Group51664001_0"
        castShadow
        receiveShadow
        geometry={nodes.Group51664001_0.geometry}
        material={materials.PaletteMaterial001}
        position={[0.687, -0.348, 0.01]}
        rotation={[1.068, 0, -0.362]}
      />
      <mesh
        name="Sphere_0"
        castShadow
        receiveShadow
        geometry={nodes.Sphere_0.geometry}
        material={materials['Material.010']}
        position={[-0.002, -2.762, -0.131]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[2.258, 2.3, 1.64]}
      />
      <primitive object={nodes.Armature_rootJoint} />
      <skinnedMesh
        name="eyes001_0"
        geometry={nodes.eyes001_0.geometry}
        material={materials['Material.013']}
        skeleton={nodes.eyes001_0.skeleton}
        position={[0.001, -0.709, -0.131]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.416}
      />
      <skinnedMesh
        name="Group39424001_0"
        geometry={nodes.Group39424001_0.geometry}
        material={materials.PaletteMaterial001}
        skeleton={nodes.Group39424001_0.skeleton}
        position={[0.001, -0.709, -0.131]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.416}
      />
      <skinnedMesh
        name="hands_0"
        geometry={nodes.hands_0.geometry}
        material={materials.Material}
        skeleton={nodes.hands_0.skeleton}
        position={[0.001, -0.709, -0.131]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.416}
      />
      <skinnedMesh
        name="shoes_0"
        geometry={nodes.shoes_0.geometry}
        material={materials.Material}
        skeleton={nodes.shoes_0.skeleton}
        position={[0.001, -0.709, -0.131]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.416}
      />
      <skinnedMesh
        name="Group39424_0"
        geometry={nodes.Group39424_0.geometry}
        material={materials.PaletteMaterial001}
        skeleton={nodes.Group39424_0.skeleton}
        position={[0.001, -0.709, -0.131]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.416}
      />
      <skinnedMesh
        name="cape-2_0"
        geometry={nodes['cape-2_0'].geometry}
        material={materials['Material.009']}
        skeleton={nodes['cape-2_0'].skeleton}
        position={[0.001, -0.709, -0.131]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.416}
      />
      <skinnedMesh
        name="cape-2_1"
        geometry={nodes['cape-2_1'].geometry}
        material={materials.PaletteMaterial001}
        skeleton={nodes['cape-2_1'].skeleton}
        position={[0.001, -0.709, -0.131]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.416}
      />
      <skinnedMesh
        name="cape-2_2"
        geometry={nodes['cape-2_2'].geometry}
        material={materials['Material.005']}
        skeleton={nodes['cape-2_2'].skeleton}
        position={[0.001, -0.709, -0.131]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.416}
      />
      <skinnedMesh
        name="body_m_0"
        geometry={nodes.body_m_0.geometry}
        material={materials.body_m}
        skeleton={nodes.body_m_0.skeleton}
        position={[0.001, -0.709, -0.131]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.416}
      />
      <skinnedMesh
        name="hat_0"
        geometry={nodes.hat_0.geometry}
        material={materials['hat-1']}
        skeleton={nodes.hat_0.skeleton}
        position={[0.001, -0.709, -0.131]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.416}
      />
      <skinnedMesh
        name="hat_1"
        geometry={nodes.hat_1.geometry}
        material={materials['hat-1']}
        skeleton={nodes.hat_1.skeleton}
        position={[0.001, -0.709, -0.131]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.416}
      />
      <skinnedMesh
        name="hat_2"
        geometry={nodes.hat_2.geometry}
        material={materials['hat-1']}
        skeleton={nodes.hat_2.skeleton}
        position={[0.001, -0.709, -0.131]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.416}
      />
      <skinnedMesh
        name="hat_3"
        geometry={nodes.hat_3.geometry}
        material={materials.PaletteMaterial001}
        skeleton={nodes.hat_3.skeleton}
        position={[0.001, -0.709, -0.131]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.416}
      />
      <mesh
        name="Sphere002_0"
        castShadow
        receiveShadow
        geometry={nodes.Sphere002_0.geometry}
        material={materials.PaletteMaterial002}
        position={[1.446, 0.467, 1.484]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.078}
      />
    </group>
  )
});

export default HatModel;
useGLTF.preload("/models/hat-transformed.glb");
